name: WhatEnchant
version: '${project.version}'
main: whatenchant.whatenchant.WhatEnchant
api-version: 1.19
authors: [ SakakiAruka ]
description: display enchantment
commands:
  enchantcheck:
    permission: whatenchant.default

permissions:
  whatenchant.default:
    default: true